services:
  Wwtrans:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/yunjian101/wwtrans
    container_name: WwTrans
    restart: always
    ports:
      - '80:80'
    environment:
      - SHOW_PUBLIC_IP=false
