server {
    listen       80;
    listen  [::]:80;

    location / {
        root   /app/web;
        index  index.html index.htm;
    }

    location /api/public-ip {
        fastcgi_pass unix:/run/fcgiwrap.sock;
        fastcgi_param SCRIPT_FILENAME /app/web/getip.cgi;
        include fastcgi_params;
        fastcgi_param REQUEST_METHOD $request_method;
    }

    location /cgi-bin/gettoken {
        proxy_pass https://qyapi.weixin.qq.com;
    }
    location /cgi-bin/message/send {
        proxy_pass https://qyapi.weixin.qq.com;
    }
    location /cgi-bin/menu/create {
        proxy_pass https://qyapi.weixin.qq.com;
    }
    location /cgi-bin/media/upload {
        proxy_pass https://qyapi.weixin.qq.com;
    }
    location /cgi-bin/media/get {
        proxy_pass https://qyapi.weixin.qq.com;
    }

}